[package]
name = "feignhttp-generator"
version = "0.1.0-26.8.26"
edition = "2021"
description = "OpenAPI to feignhttp client code generator"
license = "MIT"

[workspace]
members = ["consumer-test"]

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
toml = "1.1.4"
ureq = "3.0.11"

[[bin]]
name = "feignhttp-generator"
path = "src/main.rs"
